#!/bin/sh
printf "\n\nmnist:\n"
./evaluate_mnist.sh "$@"
printf "\n\ncifar10:\n"
./evaluate_cifar10.sh "$@"
printf "\n\ncifar100:\n"
./evaluate_cifar100.sh "$@"
printf "\n\nfashionmnist:\n"
./evaluate_fashionmnist.sh "$@"
printf "\n\nkws20:\n"
./evaluate_kws20.sh "$@"
printf "\n\nrock:\n"
./evaluate_rock.sh "$@"
